### ISSUE TITLE
lijnen niet goed toegekend aan elementen in grid

### ISSUE THREAD

**Issue by Theo-denBlanken** [steffalon/Grid-oefening#1]
```
    grid-column: 1/all;
    grid-row: 1;
```
lijkt me niet goed Hier lijken mij alle kolommen te worden gebruikt.
`grid-row: 1; ` er moet toch een begin en eind-gridlijn worden aangeduid??
Dit verklaart m.i. waarom er niets van een grid merkbaar is.
Tip: gebruik grid-area's.

**Comment by steffalon** [comment]
Alles werkt goed. Het staat ook al live. CSS validator geeft ook geen fouten.
